// АВТО-СГЕНЕРИРОВАНО из «Проверки IFC.xlsx» + реестра-зонда (workflow).
// ПУБЛИЧНО: только ID + категория + НАЗВАНИЕ + какую IFC-сущность зондировать.
// Алгоритмы и текст НПА сюда НЕ входят (приватный checks-catalog.json, локально).
import type { CheckSpec } from "./types.ts";
import type { ProbeSpec } from "./probe.ts";

export const PUBLIC_SPECS: CheckSpec[] = [
  { id: "IFC-01", category: "Форматы", name: "Формат файла IFC", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-02", category: "Классы IFC", name: "Сопоставление элементов классам IFC", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-03", category: "Классы IFC", name: "Запрет использования IfcBuildingElementProxy", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-04", category: "Форматы", name: "Соответствие схеме IFC", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-05", category: "Состав", name: "Наличие ведомости ЦИМ АГР", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-06", category: "Юридическая значимость", name: "Наличие УКЭП для каждого файла", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-07", category: "Юридическая значимость", name: "Формат хранения УКЭП", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-08", category: "Юридическая значимость", name: "Валидность УКЭП", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-09", category: "Юридическая значимость", name: "Информация в сертификате УКЭП", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-10", category: "Юридическая значимость", name: "Оформление ИУЛ (при отсутствии УКЭП)", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-11", category: "Именование файлов", name: "Соответствие маске имени файла", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-12", category: "Именование файлов", name: "Использование правильного разделителя", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-13", category: "Именование файлов", name: "Запрет недопустимых символов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-14", category: "Именование файлов", name: "Корректность поля \"Шифр вида объекта\"", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-15", category: "Именование файлов", name: "Корректность поля \"Номер объекта (корпуса)\"", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-16", category: "Именование файлов", name: "Корректность поля \"Номер подобъекта (секции)\"", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-17", category: "Именование файлов", name: "Корректность поля \"Шифр ЦИМ\"", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-18", category: "Именование файлов", name: "Корректность поля \"Шифр этапа\"", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-19", category: "Именование файлов", name: "Указание номера версии (доп. поле)", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-20", category: "Размер файлов", name: "Рекомендуемый размер файла", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-21", category: "Координация", name: "Скоординированность файлов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-22", category: "Координация", name: "Единая система координат", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-23", category: "Координация", name: "Базовая точка проекта", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-24", category: "Координация", name: "Привязка к местности", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-25", category: "Единицы измерения", name: "Масштаб 1:1", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-26", category: "Единицы измерения", name: "Точность геометрии", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-27", category: "Единицы измерения", name: "Округление размеров", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-28", category: "Уровни", name: "Формирование уровней по этажам", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-29", category: "Уровни", name: "Отметка 0,000", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-30", category: "Уровни", name: "Моделирование по отметке чистого пола", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-31", category: "Уровни", name: "Разделение уровней для разных подобъектов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-32", category: "Уровни", name: "Общий набор уровней", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-33", category: "Уровни", name: "Дополнительные уровни", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-34", category: "Уровни", name: "Минимизация количества уровней", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-35", category: "Уровни", name: "Соответствие маске имени уровня", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-36", category: "Уровни", name: "Корректность поля \"Номер подобъекта\" в уровне", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-37", category: "Уровни", name: "Корректность поля \"Номер уровня\"", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-38", category: "Уровни", name: "Корректность поля \"Наименование уровня\"", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-39", category: "Уровни", name: "Корректность поля \"Тип уровня\"", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-40", category: "Оси", name: "Наличие сетки осей", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-41", category: "Оси", name: "Наименование осей", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-42", category: "Элементы", name: "Размещение в проектном положении", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-43", category: "Элементы", name: "Поэтажная разбивка", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-44", category: "Элементы", name: "Наличие необходимых параметров", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-45", category: "Состав", name: "Наличие дисциплинарных ЦИМ", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-46", category: "Состав", name: "Разбиение по корпусам", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-47", category: "ЦИМ ПС и БиО", name: "Наличие границ земельного участка в ЦИМ ПС", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-48", category: "ЦИМ ПС и БиО", name: "Наличие рельефа в ЦИМ ПС", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-49", category: "ЦИМ ПС и БиО", name: "Наличие функционального зонирования в ЦИМ ПС", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-50", category: "ЦИМ ПС и БиО", name: "Наличие озеленения в ЦИМ БиО", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-51", category: "ЦИМ ПС и БиО", name: "Наличие покрытий в ЦИМ БиО", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-52", category: "ЦИМ ПС и БиО", name: "Наличие функциональных зон в ЦИМ БиО", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-53", category: "ЦИМ ПС и БиО", name: "Моделирование элементов на отметке рельефа", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-54", category: "ЦИМ ПС и БиО", name: "Моделирование покрытий", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-55", category: "ЦИМ ПС и БиО", name: "Отсутствие МАФ и переносных изделий", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-56", category: "ЦИМ ПС и БиО", name: "Газоны в составе покрытий", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-57", category: "ЦИМ ПС и БиО", name: "Отсутствие деревьев и кустарников", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-58", category: "ЦИМ ПС и БиО", name: "Моделирование цветников", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-59", category: "ЦИМ ПС и БиО", name: "Минимальный атрибутивный состав", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-60", category: "ЦИМ АР", name: "Содержание элементов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-61", category: "ЦИМ АР", name: "Отсутствие отделочно-интерьерных решений", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-62", category: "ЦИМ АР", name: "Моделирование объемных элементов для всего здания", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-63", category: "ЦИМ АР", name: "Размещение объемных элементов в файле АР1", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-64", category: "ЦИМ АР", name: "Наличие атрибута RUS_FNO", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-65", category: "ЦИМ АР", name: "Зонирование для подсчета площади", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-66", category: "ЦИМ АР", name: "Именование зон для подсчета площади", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-67", category: "ЦИМ АР", name: "Отсутствие зон для неэксплуатируемых помещений", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-68", category: "ЦИМ АР", name: "Моделирование наружных ограждающих конструкций", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-69", category: "ЦИМ АР", name: "Классификация элементов по IFC", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-70", category: "ЦИМ АР", name: "Минимальный атрибутивный состав", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-71", category: "ЦИМ АР", name: "Минимальный набор атрибутов для отсутствующих элементов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-72", category: "ЦИМ АР", name: "Учет только пользовательских атрибутов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-73", category: "ЦИМ АР", name: "Наименование пользовательских атрибутов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-74", category: "ЦИМ АР", name: "Игнорирование стандартных наборов атрибутов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-75", category: "ЦИМ АР", name: "Наличие аннотаций (при необходимости)", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-76", category: "Аннотации", name: "Соответствие ГОСТ Р 21.101-2020", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-77", category: "Аннотации", name: "Формат аннотаций", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-78", category: "Аннотации", name: "Содержание файлов BCF", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-79", category: "Аннотации", name: "Наличие GUID в файлах разметки", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-80", category: "Аннотации", name: "Наименование файлов аннотаций", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-81", category: "Аннотации", name: "Пространственная привязка аннотаций", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-82", category: "Аннотации", name: "Наименование планов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-83", category: "Аннотации", name: "Наименование разрезов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-84", category: "Аннотации", name: "Нумерация видов изображений", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-85", category: "Подготовка к экспорту", name: "Актуальность файлов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-86", category: "Подготовка к экспорту", name: "Соответствие 2D-документации", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-87", category: "Подготовка к экспорту", name: "Отсутствие лишних элементов", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-88", category: "Подготовка к экспорту", name: "Проверка на коллизии", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-89", category: "ТЭП", name: "Возможность формирования ТЭП", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-90", category: "ТЭП", name: "Источник данных для ТЭП", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-91", category: "ТЭП", name: "Состав ТЭП", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-92", category: "Атрибуты (Приложение 1)", name: "Атрибутивный состав ЦИМ ПС и БиО", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
  { id: "IFC-93", category: "Атрибуты (Приложение 2)", name: "Атрибутивный состав ЦИМ АР", source: "", algorithm: "", priority: "", complexity: "", automatable: "", mode: "auto" },
];

export const PROBE_MAP: Record<string, ProbeSpec> = {
  "IFC-01": { id: "IFC-01", needs: "header", ifcTarget: "FILE_DESCRIPTION ViewDefinition", applicable: true, note: "" },
  "IFC-02": { id: "IFC-02", needs: "entity", ifcTarget: "IfcProduct", applicable: true, note: "" },
  "IFC-03": { id: "IFC-03", needs: "entity", ifcTarget: "IfcBuildingElementProxy", applicable: true, note: "" },
  "IFC-04": { id: "IFC-04", needs: "header", ifcTarget: "FILE_SCHEMA", applicable: true, note: "" },
  "IFC-05": { id: "IFC-05", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-06": { id: "IFC-06", needs: "manual", ifcTarget: "", applicable: false, note: "" },
  "IFC-07": { id: "IFC-07", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-08": { id: "IFC-08", needs: "manual", ifcTarget: "", applicable: false, note: "" },
  "IFC-09": { id: "IFC-09", needs: "manual", ifcTarget: "", applicable: false, note: "" },
  "IFC-10": { id: "IFC-10", needs: "manual", ifcTarget: "", applicable: false, note: "" },
  "IFC-11": { id: "IFC-11", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-12": { id: "IFC-12", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-13": { id: "IFC-13", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-14": { id: "IFC-14", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-15": { id: "IFC-15", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-16": { id: "IFC-16", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-17": { id: "IFC-17", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-18": { id: "IFC-18", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-19": { id: "IFC-19", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-20": { id: "IFC-20", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-21": { id: "IFC-21", needs: "georef", ifcTarget: "IfcGeometricRepresentationContext", applicable: true, note: "" },
  "IFC-22": { id: "IFC-22", needs: "georef", ifcTarget: "IfcGeometricRepresentationContext.TrueNorth", applicable: true, note: "" },
  "IFC-23": { id: "IFC-23", needs: "entity", ifcTarget: "IfcGrid", applicable: true, note: "" },
  "IFC-24": { id: "IFC-24", needs: "georef", ifcTarget: "IfcMapConversion", applicable: true, note: "" },
  "IFC-25": { id: "IFC-25", needs: "units", ifcTarget: "IfcUnitAssignment", applicable: true, note: "" },
  "IFC-26": { id: "IFC-26", needs: "property", ifcTarget: "IfcElementQuantity / IfcPhysicalQuantity", applicable: true, note: "" },
  "IFC-27": { id: "IFC-27", needs: "units", ifcTarget: "IfcSIUnit.Prefix / IfcQuantityLength.LengthValue", applicable: true, note: "" },
  "IFC-28": { id: "IFC-28", needs: "entity", ifcTarget: "IfcBuildingStorey", applicable: true, note: "" },
  "IFC-29": { id: "IFC-29", needs: "attribute", ifcTarget: "IfcBuildingStorey.Elevation", applicable: true, note: "" },
  "IFC-30": { id: "IFC-30", needs: "attribute", ifcTarget: "IfcBuildingStorey.Elevation", applicable: true, note: "" },
  "IFC-31": { id: "IFC-31", needs: "entity", ifcTarget: "IfcBuildingStorey", applicable: true, note: "" },
  "IFC-32": { id: "IFC-32", needs: "entity", ifcTarget: "IfcBuildingStorey.Name", applicable: true, note: "" },
  "IFC-33": { id: "IFC-33", needs: "entity", ifcTarget: "IfcBuildingStorey", applicable: true, note: "" },
  "IFC-34": { id: "IFC-34", needs: "entity", ifcTarget: "IfcBuildingStorey", applicable: true, note: "" },
  "IFC-35": { id: "IFC-35", needs: "attribute", ifcTarget: "IfcBuildingStorey.Name", applicable: true, note: "" },
  "IFC-36": { id: "IFC-36", needs: "attribute", ifcTarget: "IfcBuildingStorey.Name", applicable: true, note: "" },
  "IFC-37": { id: "IFC-37", needs: "attribute", ifcTarget: "IfcBuildingStorey.Name", applicable: true, note: "" },
  "IFC-38": { id: "IFC-38", needs: "attribute", ifcTarget: "IfcBuildingStorey.Name", applicable: true, note: "" },
  "IFC-39": { id: "IFC-39", needs: "attribute", ifcTarget: "IfcBuildingStorey.Name", applicable: true, note: "" },
  "IFC-40": { id: "IFC-40", needs: "entity", ifcTarget: "IfcGrid", applicable: true, note: "" },
  "IFC-41": { id: "IFC-41", needs: "attribute", ifcTarget: "IfcGridAxis.AxisTag", applicable: true, note: "" },
  "IFC-42": { id: "IFC-42", needs: "attribute", ifcTarget: "IfcProduct.ObjectPlacement", applicable: true, note: "" },
  "IFC-43": { id: "IFC-43", needs: "entity", ifcTarget: "IfcRelContainedInSpatialStructure", applicable: true, note: "" },
  "IFC-44": { id: "IFC-44", needs: "pset", ifcTarget: "IfcPropertySet", applicable: true, note: "" },
  "IFC-45": { id: "IFC-45", needs: "filename", ifcTarget: "", applicable: false, note: "" },
  "IFC-46": { id: "IFC-46", needs: "filename", ifcTarget: "", applicable: false, note: "" },
  "IFC-47": { id: "IFC-47", needs: "annotation", ifcTarget: "IfcAnnotation", applicable: true, note: "" },
  "IFC-48": { id: "IFC-48", needs: "entity", ifcTarget: "IfcGeographicElement / IfcSite.Representation", applicable: true, note: "" },
  "IFC-49": { id: "IFC-49", needs: "entity", ifcTarget: "IfcSpace / IfcZone", applicable: true, note: "" },
  "IFC-50": { id: "IFC-50", needs: "entity", ifcTarget: "IfcGeographicElement / IfcSlab", applicable: true, note: "" },
  "IFC-51": { id: "IFC-51", needs: "entity", ifcTarget: "IfcSlab / IfcCovering", applicable: true, note: "" },
  "IFC-52": { id: "IFC-52", needs: "entity", ifcTarget: "IfcSpace / IfcZone", applicable: true, note: "" },
  "IFC-53": { id: "IFC-53", needs: "georef", ifcTarget: "IfcSlab/IfcSpace.ObjectPlacement vs IfcSite рельеф", applicable: true, note: "" },
  "IFC-54": { id: "IFC-54", needs: "entity", ifcTarget: "IfcSlab геометрия: SweptSolid толщина / Tessellation по рельефу", applicable: true, note: "" },
  "IFC-55": { id: "IFC-55", needs: "entity", ifcTarget: "IfcFurnishingElement / IfcFurniture / IfcGeographicElement", applicable: true, note: "" },
  "IFC-56": { id: "IFC-56", needs: "material", ifcTarget: "IfcSlab.HasAssociations -> IfcMaterial", applicable: true, note: "" },
  "IFC-57": { id: "IFC-57", needs: "entity", ifcTarget: "IfcGeographicElement деревья/кустарники", applicable: true, note: "" },
  "IFC-58": { id: "IFC-58", needs: "entity", ifcTarget: "IfcSlab/IfcCovering", applicable: true, note: "" },
  "IFC-59": { id: "IFC-59", needs: "pset", ifcTarget: "RusSet_*/RUS_* пользовательские Pset элементов ЦИМ ПС/БиО", applicable: true, note: "" },
  "IFC-60": { id: "IFC-60", needs: "entity", ifcTarget: "IfcSpace, IfcWall, IfcSlab, IfcCovering, IfcOpeningElement, IfcStair, IfcGrid", applicable: true, note: "" },
  "IFC-61": { id: "IFC-61", needs: "entity", ifcTarget: "IfcCovering", applicable: true, note: "" },
  "IFC-62": { id: "IFC-62", needs: "entity", ifcTarget: "IfcBuildingElementProxy", applicable: true, note: "" },
  "IFC-63": { id: "IFC-63", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-64": { id: "IFC-64", needs: "property", ifcTarget: "Pset RusSet_*.RUS_FNO", applicable: true, note: "" },
  "IFC-65": { id: "IFC-65", needs: "entity", ifcTarget: "IfcSpace", applicable: true, note: "" },
  "IFC-66": { id: "IFC-66", needs: "property", ifcTarget: "Pset RusSet_*.RUS_Name", applicable: true, note: "" },
  "IFC-67": { id: "IFC-67", needs: "entity", ifcTarget: "IfcSpace", applicable: true, note: "" },
  "IFC-68": { id: "IFC-68", needs: "entity", ifcTarget: "IfcCurtainWall", applicable: true, note: "" },
  "IFC-69": { id: "IFC-69", needs: "classification", ifcTarget: "IfcSpace / IfcWall / IfcSlab / IfcDoor / IfcWindow", applicable: true, note: "" },
  "IFC-70": { id: "IFC-70", needs: "pset", ifcTarget: "IfcPropertySet RusSet_* / RUS_*", applicable: true, note: "" },
  "IFC-71": { id: "IFC-71", needs: "pset", ifcTarget: "IfcPropertySet RusSet_* / RUS_*", applicable: true, note: "" },
  "IFC-72": { id: "IFC-72", needs: "pset", ifcTarget: "IfcPropertySet.Name", applicable: true, note: "" },
  "IFC-73": { id: "IFC-73", needs: "property", ifcTarget: "IfcPropertySet.Name / IfcProperty.Name", applicable: true, note: "" },
  "IFC-74": { id: "IFC-74", needs: "property", ifcTarget: "IfcPropertySet.Name", applicable: true, note: "" },
  "IFC-75": { id: "IFC-75", needs: "annotation", ifcTarget: "IfcAnnotation", applicable: true, note: "" },
  "IFC-76": { id: "IFC-76", needs: "manual", ifcTarget: "", applicable: false, note: "" },
  "IFC-77": { id: "IFC-77", needs: "annotation", ifcTarget: "BCF + IfcAnnotation ObjectType=растровое изображение", applicable: false, note: "" },
  "IFC-78": { id: "IFC-78", needs: "manual", ifcTarget: "", applicable: false, note: "" },
  "IFC-79": { id: "IFC-79", needs: "other", ifcTarget: "BCF Topic Guid", applicable: false, note: "" },
  "IFC-80": { id: "IFC-80", needs: "filename", ifcTarget: "имя файла", applicable: false, note: "" },
  "IFC-81": { id: "IFC-81", needs: "annotation", ifcTarget: "BCF Viewpoint + IfcGeometricRepresentationContext.WorldCoordinateSystem", applicable: false, note: "" },
  "IFC-82": { id: "IFC-82", needs: "annotation", ifcTarget: "IfcAnnotation.Name", applicable: true, note: "" },
  "IFC-83": { id: "IFC-83", needs: "annotation", ifcTarget: "IfcAnnotation.Name", applicable: true, note: "" },
  "IFC-84": { id: "IFC-84", needs: "annotation", ifcTarget: "IfcAnnotation.Name / BCF Topic.Title", applicable: true, note: "" },
  "IFC-85": { id: "IFC-85", needs: "manual", ifcTarget: "", applicable: false, note: "" },
  "IFC-86": { id: "IFC-86", needs: "manual", ifcTarget: "", applicable: false, note: "" },
  "IFC-87": { id: "IFC-87", needs: "entity", ifcTarget: "IfcElement + IfcAnnotation", applicable: true, note: "" },
  "IFC-88": { id: "IFC-88", needs: "manual", ifcTarget: "", applicable: false, note: "" },
  "IFC-89": { id: "IFC-89", needs: "property", ifcTarget: "IfcElementQuantity / BaseQuantities — наличие количественных величин у IfcSpace/IfcSlab/IfcSite", applicable: true, note: "" },
  "IFC-90": { id: "IFC-90", needs: "pset", ifcTarget: "RusSet_* + IfcElementQuantity на элементах", applicable: true, note: "" },
  "IFC-91": { id: "IFC-91", needs: "property", ifcTarget: "IfcSpace + IfcSite + RUS_*/Qto-величины высоты застройки", applicable: true, note: "" },
  "IFC-92": { id: "IFC-92", needs: "pset", ifcTarget: "RusSet_* свойства на элементах ПС/БиО: RUS_MSSK_Element_Code, RUS_Name, RUS_Area", applicable: true, note: "" },
  "IFC-93": { id: "IFC-93", needs: "pset", ifcTarget: "RusSet_* свойства по классам АР: IfcSpace/IfcWall/IfcSlab/IfcDoor/IfcWindow/IfcBuildingElementProxy", applicable: true, note: "" },
};
